### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by dsimba** [mfrdixon/dq-MM#1]
I tried to run an example code. But I am getting this error. Any help? Thanks

I am using Python 3.7 with Anaconda

Traceback (most recent call last):
  File "DQNAgent.py", line 152, in <module>
    history_length=history_length)
  File "C:\Users\autom\Anaconda3\lib\site-packages\tgym-0.1.14-py3.7.egg\tgym\envs\trading.py", line 62, in __init__
    self.reset()
  File "C:\Users\autom\Anaconda3\lib\site-packages\tgym-0.1.14-py3.7.egg\tgym\envs\trading.py", line 80, in reset
    gen = np.array(self._data_generator.next())
  File "C:\Users\autom\Anaconda3\lib\site-packages\tgym-0.1.14-py3.7.egg\tgym\core.py", line 71, in next
    return self.generator.next()
AttributeError: 'generator' object has no attribute 'next'

**Comment by mfrdixon** [comment]
Hi there,

Please can you try a different repository - this one is not maintained. You
can run a similar application from here:
https://github.com/mfrdixon/ML_Finance_Codes/blob/master/Chapter9-Reinforcement-Learning/ML_in_Finance_MarketMaking.ipynb

However, please see the installation instructions at the folder root level
(README.md) to ensure that your stack is set up correctly with the same
virtual env.

Matthew
